[package]
name = "c_sharp_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib","cdylib","rlib"]

[dependencies]

[build-dependencies]
cbindgen = "0.24"